name: Build and Release

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: '构建类型'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev
          - preview
          - blank-test

env:
  NODE_VERSION: 22.x
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUILD_TYPE: ${{ github.event.inputs.buildType || 'dev' }}
      EAS_PROFILE: ${{ github.event.inputs.buildType == 'prod' && 'prod-ci' || 'preview' }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🤖 Setup PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🤖 Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ env.EXPO_TOKEN }}
          packager: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: ⚙️ Prepare Variables
        run: |
          APP_VERSION=$(node -p "require('./apps/mobile/package.json').version")
          VERSION_CODE=$(git rev-list --count HEAD)
          APK_NAME="bbplayer-v${APP_VERSION}-${{ env.BUILD_TYPE }}-arm64-v8a"
          echo "APK_NAME=${APK_NAME}" >> $GITHUB_ENV
          echo "APK_TEMP_PATH=${RUNNER_TEMP}/${APK_NAME}.apk" >> $GITHUB_ENV
          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV

      - name: 🚀 Build APK (EAS local)
        if: env.BUILD_TYPE != 'blank-test'
        run: |
          cd apps/mobile
          eas build --platform android --profile ${{ env.EAS_PROFILE }} --local --output="${{ env.APK_TEMP_PATH }}" 2>&1

      - name: 🧪 Create Dummy APK
        if: env.BUILD_TYPE == 'blank-test'
        run: echo "dummy" > "${{ env.APK_TEMP_PATH }}"

      - name: 🚀 Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_TEMP_PATH }}
          if-no-files-found: error
